apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress-pod

  template:
    metadata:
      labels:
        app: wordpress-pod
    spec:
      containers:
      - image: wordpress:5.8.2-apache
        name: wordpress
        ports:
        - containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
            value: "mysql-service:3306"
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql_wordpress_user
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql_wordpress_password
          - name: WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql_db_name  
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress-pod